title: Renyuan Chen's Homepage
page-top-title: Renyuan Chen
top-section-bg-text: Transportation Engineering
home-subtitle: Renyuan Chen&ensp;|&ensp;李森
copyright-text: '&copy; Renyuan Chen 2025. All Rights Reserved.'
